.gitignore, .travis.yml, Manifest.toml, Project.toml, README.md, bin/test.jl, deps/Builds.toml, deps/Registries.toml, deps/Versions.toml, src/NewPkgEval.jl, src/build.jl, src/julia.jl, src/registry.jl, src/run.jl, test/runtests.jl
The goal would be for some cron-job to just target `1.3-latest` and have it work as expected (similar to how `build_julia` currently checks out and returns a version number, but minus the building).
=> Differentiate between versions (version, file, sha) and builds (name, url)

Manifest.toml, Project.toml, README.md, bin/test.jl, runner/Dockerfile, src/NewPkgEval.jl, src/julia.jl, src/registry.jl, src/run.jl, test/runtests.jl
Although BB's UserNS sandbox is nice, being Alpine (musl) based gives issues with several packages. Furthermore, with Docker it's much easier to use, e.g., GPUs, and install whatever dependencies packages require.
Also fixes https://github.com/JuliaComputing/NewPkgEval.jl/issues/16
=> Use Docker for sandboxing

deps/Registries.toml, src/registry.jl, src/run.jl
Fixes https://github.com/JuliaComputing/NewPkgEval.jl/issues/40
I decided only to retry packages with test failures, even though the most recent daily has a couple of other packages that regularly fail but with much more serious error (e.g. segmentation faults). I don't think we should retry and hide those.
=> Support for retrying packages.

runner/Dockerfile
Fixes #47 
This is necessary for the test suites of the following packages:
- PGFPlotsX.jl
- PredictMD.jl
=> Install texlive in the Docker image

Project.toml
This pull request adds the following `[compat]` entry to the `Project.toml` file:
```toml
julia = "1"
```
This is consistent with the advice that we give to package authors.
=> Add compat entry for Julia

src/run.jl
Currently, we set the `CI` and `PKGEVAL` environment variables.
It has occured to me that neither of these are Julia-specific. `CI` is certainly a common environment variable, and I suppose that there could be other pieces of software named `PKGEVAL`.
I think it would be really nice for NewPkgEval to also set an environment variable that is unambiguously specific to the Julia package evaluation infrastructure. So this PR sets the "JULIA_PKGEVAL" to "true".
=> Set the environment variable "JULIA_PKGEVAL" to "true"

runner/Dockerfile, src/run.jl
This PR runs Julia under `xvfb-run`. This should fix all of the packages that are failing because they need a display. One example of such a package is Gtk.jl (example log [here](https://github.com/maleadt/BasePkgEvalReports/blob/8afa60b4129a965cd82085b3c454854b11619a0e/pkgeval-daily_2019_12_30/logs/Gtk/1.4.0-DEV-032dbe33e3.log)).
=> Run Julia under `xvfb-run`

Manifest.toml, Project.toml, src/run.jl
Use tmpfs to cut down on I/O and filesystem load (which might have been causing some issues on arctic). It's mounted `exec`, but still `nosuid,nodev`. I would think no package requires that though.
Also restrict each job to a single CPU, since some tests use everything available and might cause timeouts on other tests.
=> Tweaks to Docker environment

.gitignore, deps/Versions.toml, src/NewPkgEval.jl, src/julia.jl, src/registry.jl, src/run.jl
=> Don't mutate pkg dir, use cache dir instead (and put artifacts in it)

runner/Dockerfile, src/run.jl
E.g. if you look at the PyCall tests, you'll notice that it uses the system Python, and the tests fail: https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2020-08/26/logs/PyCall/1.6.0-DEV-5da96913c2.log
This PR forces Julia to install its own Python and its own R.
cc: @maleadt
=> Set `ENV["PYTHON"] = ""` and `ENV["R_HOME"] = "*"`

src/run.jl
Previously this may stop reading the last 4-64kb of the log if the test prints a few lines quickly near the end.
=> Read the log tail without fail

Artifacts.toml, rootfs/arch.sh, src/report.jl, src/run.jl, test/runtests.jl
Initial stab at https://github.com/JuliaCI/PkgEval.jl/issues/79. Uses PackageCompiler to generate a custom systemimage that includes the package we're interested in (albeit without any precompilation statements, but I don't think that matters). It then uses that system image to run tests, but in a slightly different container (Arch Linux based) and with a different depot.
TODO:
=> Compiled mode: Run tests with custom system image

.github/workflows/ci.yml, src/evaluate.jl, src/julia.jl, test/runtests.jl
I noticed some slowdown after adding a shared compilecache to Nanosoldier, and I'm thinking this may be due to workers running into one another while precompiling packages. So let's try this out: packages are precompiled into a local compilecache (`~/.julia/.../compiled`), and after completion copied into a global cache that's mounted read-only at the system depot (`/usr/local/share/julia`).
@vtjnash Any thoughts? The reason I want to share the compile cache, is that when running under `--bug-report` we otherwise precompile BugReporting.jl's dependencies over and over again. This makes e.g. Example.jl take 30 sec to install/test, whereas it normally only takes 3. Sharing the compilecache gets it down to ~10 sec.
=> Use a local compilecache, sync after execution.

Artifacts.toml, src/evaluate.jl, src/julia.jl, src/rootfs.jl, src/types.jl
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/5319#issuecomment-1222342187.
Ref https://github.com/JuliaCI/rootfs-images/issues/216
=> Switch to Base CI rootfs for building Julia.

Packages.toml, src/PkgEval.jl, src/evaluate.jl, src/registry.jl, src/types.jl
Instead of maintaining a list of packages to retry, this PR makes it so that PkgEval retries all packages that failed in one or more (but not all) configurations. I'm not entirely sure this is what we want (it might blow up test time if it ends up retrying packages that hit the time limit), and whether we want this by default or not, but we can give this a try and see how it goes.
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/122
=> Retry packages that fail in one configuration

src/evaluate.jl, src/registry.jl, src/types.jl
Turns out lots of packages do this, which breaks the way we cache packages in a layered, read-only depot. So as a workaround, copy the package we're testing from the global, read-only depot dir into the local, mutable one.
=> Work around packages mutating their own files

src/sandbox.jl, src/types.jl, test/runtests.jl
For https://github.com/JuliaLang/julia/pull/46372
=> Add a configuration flag for setting the environment

src/evaluate.jl
This should make it easier for Nanosoldier to report these prominently: Especially in the case of dailies, if a test crashed spectacularly, we shouldn't hide it under "also failed on the previous commit".
=> Separately classify crashes.

src/evaluate.jl
Currently we're starting a whole new evaluation in order to retry certain failed packages, which is wasteful because each evaluation often ends with a long tail of packages that take a very long time (i.e., not running in parallel with many other packages). So instead, interleave the retries with the main evaluation in order to optimize parallel execution.
WIP because I want to refactor some things in light of this.
=> Interleave retries

src/evaluate.jl, src/types.jl, test/runtests.jl
Cachine packages with a `deps/build` folder is invalid (the build step doesn't re-run if we install the package the next time), so if we retry we should do so in a pristine environment that doesn't use cached packages/artifacts.
=> Retry packages in a pristine environment.

src/evaluate.jl, src/sandbox.jl
This because `Pkg.test` sometimes doesn't throw when we encounter an internal error, so currently the logic that does an `rr pack` doesn't trigger. By persisting the executor and re-starting the container after we've accurately determined the crash reason (without having to run `Pkg.test` under `redirect_stdio` or so) we now also `rr pack` and upload for non-fatal crashes.
=> Run rr pack separately

.github/workflows/ci.yml, src/evaluate.jl, test/runtests.jl
I had included this in the Buildkite PR, but it seems to cause segfaults, so let's investigate.
=> Set JULIA_PRECOMPILE=0 to speed-up CI.

src/evaluate.jl
If a package isn't installable, or doesn't have tests, we shouldn't mark it as `fail` but as `skip`.
=> Treat more packages as 'skipped'

src/evaluate.jl
We shouldn't bother sending SIGINT -- systemd goes directly to SIGTERM, and Julia doesn't handle SIGINT well anyway.
We can also try and detect SIGSEGV and SIGABRT from the exit code (128 + SIGNUM) instead of only relying on the logs, for the unlikely case where Julia's signal handlers aren't working. This will matter more for SIGKILL detection, where we don't have such a handler.
=> Improve test kill & crash detection

src/evaluate.jl, src/sandbox.jl
`include_string` gives slightly better stack traces, and is what 1.8 uses when you pass `-` (i.e. read from STDIN).
=> Improve script include and color handling

src/evaluate.jl
This simplifies debugging PkgEval, because we at least get an incomplete dataframe.
=> Finish evaluate_test with :kill on CTRL-C.

src/evaluate.jl, test/runtests.jl
The goal is to have Nanosoldier.jl provide an additional blacklist, generated here: https://github.com/JuliaCI/NanosoldierReports/commit/54e61b9e1731eff14941add58cb18606817f3df8.
=> Generalize the skip mechanism to a configurable blacklist.

src/utils.jl
Apparently the kernel throws both ENOENT and ESRCH when a task doesn't exist, and I couldn't find any consistency in what is thrown when, so just check for both errors.
=> Check for ESRCH when accessing procfs.

src/evaluate.jl
We already detect segfaults and aborts when the test process signals, and when the log contains the output from the sigdie handler, but apparently it's possible that the sigdie handler doesn't trigger, e.g., https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d01c691_vs_427432e/Ripserer.primary.log. Pkg does know about the inner process having exited with a signal though, and reports that, so update out log parsing regexes.
=> Classify crashes based on Pkg signal reporting.

src/evaluate.jl
> https://github.com/JuliaLang/julia/pull/47184 will cause precompilation to occur again if certain flags (notably, checkbounds) are changed. So we wait to precompile until all flags are known.
=> Don't precompile packages during Pkg.add.

.github/workflows/ci.yml, src/PkgEval.jl, src/registry.jl, src/types.jl
By using a token, and checking out the registry from a PkgServer.
=> Avoid GitHub rate limits

Packages.toml
The problems from https://github.com/yeesian/ArchGDAL.jl/issues/347 seem to be all fixed and tagged now. I cannot run the PkgEval sandbox from WSL (`ERROR: Failed to start Xvfb`), but locally on 1.9.0-beta2 all tests pass.
=> stop skipping ArchGDAL

src/evaluate.jl, src/sandbox.jl, test/runtests.jl
Turns out https://github.com/JuliaCI/PkgEval.jl/pull/201 had a problem: because it resulted in precompilation happening during `Pkg.test`, it broke the test time measurement (which I intend to use as an ecosystem-wide performance regression test).
As an alternative approach, call `Pkg.precompile` manually again, but in a Julia shell we launched using the correct options (to avoid redundant compilation). @vchuravy which options exactly are relevant?
TODO: maybe add a test that on 1.9+ we only generate a single .so when testing, say, Example.jl
=> Separate out precompilation

src/evaluate.jl, test/runtests.jl
This makes it possible to test blacklisted packages, when specifically requesting it.
cc @KristofferC
=> Only blacklist packages when testing the entire ecosystem.

src/evaluate.jl, src/registry.jl
Ideal would be looking up which version is compatible for the different Julia builds we're using, but this is much simpler. It ensures we always test the same code on each Julia version.
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/208
=> Explicitly test the latest version of each package

src/evaluate.jl, src/julia.jl, src/types.jl, test/runtests.jl
If this works, I want to disable using `rr` for all tests in the daily evaluations. It's very expensive, and although this may result in us missing rare/nondeterministic crashes, I don't think we can keep up with the ecosystem growth if daily PkgEval runs already take over 12h.
=> Retry crashes under rr.

Packages.toml
This reverts commit ff51af05238e92f0e027dcd5ed0f55aee2160b7d.
Fixed on `main` upstream by https://github.com/JuliaTesting/ReTestItems.jl/pull/40
=> Revert "Blacklist ReTestItems.jl"

Packages.toml
@maleadt The latest release (v1.1.3) of `Fronts` no longer depends on `ResumableFunctions` (https://github.com/BenLauwens/ResumableFunctions.jl/issues/60)
=> Remove Fronts.jl blacklist

Packages.toml
No longer depends on ResumableFunctions as of FoldRNA v0.1.1
=> Remove FoldRNA from Packages.toml skip list

Packages.toml
As reported in https://github.com/BenLauwens/ResumableFunctions.jl/issues/60 ResumableFunctions.jl was relying on internal julia implementation details that changed in 1.10. A fix is now upstreamed and released as non-breaking (v0.6.2).
=> remove ResumableFunctions and dependents from blacklist

Packages.toml
It's flakey (see: https://github.com/tkoolen/LoopThrottle.jl/issues/10, https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/94a56d2_vs_fb76136/LoopThrottle.primary.log) and hasn't been updated in years, but does have 11 dependants.
=> Skip LoopThrottle.jl

src/evaluate.jl, src/registry.jl
Now that Pkg has been removed from the sysimg, we need to use pkgimages or every Pkg operation will be slow and cause a lot of compilation.
cc @KristofferC
=> Re-enable pkgimages

src/utils.jl
The `stable` name is used for package testing, but since Nanosoldier now also requests assertions to be enabled (https://github.com/JuliaCI/Nanosoldier.jl/pull/183) that gets passed to the build functionality. Make sure that knows how to deal with `stable` by looking up the latest tag.
=> Add support for building the 'stable' version.

src/sandbox.jl
Now that the default depot isn't added automatically anymore, we should do so ourselves, making it possible to put it in the correct spot.
=> Adapt to JuliaLang/julia#51448.

Packages.toml
Julia 1.10 was released while still breaking CodeTracking (due to a parser change, https://github.com/JuliaLang/JuliaSyntax.jl/issues/316#issuecomment-1870294857). I was deliberately not fixing this issue assuming it would be noticed and investigated during the 1.10 PkgEval runs, but it seems to have either been decided to be unimportant or simply not noticed. EDIT: LoweredCodeUtils tests are broken, too.
While this is not actually a big deal, given that these packages both underlie Revise and extensively test internals, perhaps it makes sense to ensure they don't get blacklisted.
=> Add Revise's dependencies to "important packages"

scripts/precompile.jl, scripts/report_bug.jl, scripts/test.jl, src/evaluate.jl
If the test process succeeded, we would re-execute the tests. Avoid that by including an `exit(0)`.
However, PkgEval proper doesn't seem to collect rr traces anymore. I've included some logging to debug that.
Also hides some irrelevant Pkg output by overriding `Pkg.DEFAULT_IO`. Hope that's portable...
=> rr-related improvements

src/rootfs.jl
=> Index the rootfs download cache by artifact hash, not by filename.

Packages.toml
This is an old and unmaintained package (https://github.com/jw3126/UnitfulRecipes.jl/pull/81), so even if we had to fix anything in that package, nothing could be done about it.  Note: this is currently failing tests in https://github.com/JuliaLang/julia/pull/53891#issuecomment-2040626771 because it's trying to install a very ancient version of `GR.jl`, I don't see any fix possible if the package is deprecated.
=> Skip `UnitfulRecipes`

Packages.toml
I'd like to propose that we add [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) to the list of "important packages" for PkgEval.
=> Add PackageCompiler to the "important package" list

src/evaluate.jl
The goal here is to get PackageCompiler passing again on PkgEval nightly.
=> Give "slow" packages even more time

bin/test_package.jl, scripts/compile.jl, scripts/test.jl, src/PkgEvalCore.jl, src/evaluate.jl, src/sandbox.jl, test/runtests.jl
This defeats Pkg.jl's `gen_subprocess_cmd` overriding flags like `--check-bounds` with an unconditional `yes`, as well as `Base.julia_cmd` not reporting flags like `--inline`. With this, it should be possible to run PkgEval with `--check-bounds=no`, as requested in https://github.com/JuliaLang/julia/pull/55913.
=> Forward Julia arguments to Pkg.test

src/evaluate.jl
Reverts JuliaCI/PkgEval.jl#267
Looks like PackageCompiler legitimately hangs, so there's no need to extend the timeout.
https://github.com/JuliaLang/julia/commit/6cb9f04
=> Revert "Give "slow" packages even more time"

Packages.toml
This is one of my packages. It does some pointer stuff that's illegal (which I didn't know was), and so started segfaulting on 1.11. E.g. [here, segfaulting on a recent PkgEval run](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/790081c_vs_4976d05/report.html).
Ideally I'd just fix the package, but it's turned out to be harder than I expected, so blacklisting it for now.
=> Blacklist ScanByte.jl

bin/test_package.jl, scripts/evaluate.jl, scripts/precompile.jl, src/PkgEvalCore.jl, src/evaluate.jl, test/runtests.jl
Use that as the fallback for blacklisted packages.
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/271
Will only deploy next week.
=> Make it possible to evaluate package loadability.

src/utils.jl, test/runtests.jl
On RHEL derivatives, here is example output for `uname -r`:
```
$ uname -r
4.18.0-553.60.1.el8_10.x86_64
```
This PR makes it so that `get_kernel_version()` can parse that kind of output.
=> Fix `get_kernel_version()` on RHEL derivatives
