JuliaCI/PkgEval.jl

src/NewPkgEval.jl
This adds a few docstrings to functions with basic descriptions of the interface and functionality.
=> Add some basic documentation

.travis.yml, Manifest.toml, Project.toml, README.md, src/NewPkgEval.jl, src/build_julia.jl, test/runtests.jl
=> simplify (remove) scheduler based on dependency graph

Manifest.toml, Project.toml, README.md, bin/test.jl, runner/Dockerfile, src/julia.jl, src/registry.jl, src/run.jl, test/runtests.jl
return `status=skipped, reason=unsupported` if no Julia version is compatible with the package.
=> Check Julia version compatibility

src/julia.jl
With this, it's possible to `NewPkgEval.obtain_julia_build("pull/$pr/merge")`
=> Support for fetching remote refs.

src/run.jl
We were cloning it every time, as spotted by different Graphics.jl versions in a single run.
=> Fix the registry mount point, make it user independent.

deps/Registries.toml
Many of these packages have been purged from the registry and we have functionality that kills hanging jobs now so I think we should start with a fresh start with this list again.
=> empty skip list

README.md, src/NewPkgEval.jl, src/run.jl, test/runtests.jl
Part of https://github.com/JuliaComputing/NewPkgEval.jl/issues/41.
=> Don't write logs to disk.

.travis.yml, Manifest.toml, Project.toml, src/run.jl
Address https://github.com/JuliaComputing/NewPkgEval.jl/issues/55
Not sure what the error in https://travis-ci.com/JuliaComputing/NewPkgEval.jl/jobs/271476640 was caused by, but bumping BB might fix that.
=> Bump BinaryBuilder, make CI build from source

.travis.yml, test/runtests.jl
Fixes https://github.com/JuliaComputing/NewPkgEval.jl/issues/57
=> Test Gtk.jl for X11 support.

src/julia.jl
Both to prevent caching old commits locally.
Ref https://github.com/JuliaLang/julia/pull/34272#issuecomment-572473388
=> Don't create local branches for remote refs, and prune while fetching.

README.md, src/NewPkgEval.jl, src/julia.jl, src/run.jl, test/runtests.jl
Hopefully works around https://github.com/JuliaComputing/NewPkgEval.jl/issues/72
=> Extract Julia in temporary dir, not the cache.

runner/Dockerfile, src/NewPkgEval.jl, src/run.jl
Requires something like https://github.com/JuliaLang/julia/commit/58605d37023a99d469eefe7086b82683aa1b2057
=> Improve cache handling, for precompile files

deps/Registries.toml
This should reduce a bit of noise.
=> Exclude some packages that won't work on PkgEval or are deprecated

.github/workflows/ci.yml, runner/Dockerfile.arch, runner/Dockerfile.ubuntu, runner/entrypoint.sh, src/report.jl, src/run.jl, test/runtests.jl
Backport NFC changes from https://github.com/JuliaCI/PkgEval.jl/pull/80.
=> Introduce a Config object, and other clean-ups.

deps/Registries.toml
BitemporalPostgres requires POSTGRES
=> added BitemporalPostgres

src/evaluate.jl, test/runtests.jl
Makes it easier to identify the configuration that run a test, instead of having to save all config properties in the dataframe.
=> Put the name of the configuration in the output dataframe.

src/evaluate.jl, src/julia.jl, src/registry.jl, src/types.jl, src/utils.jl
=> Make the registry configurable.

src/julia.jl
Only provide it when the user isn't specifying it as a build flag.
=> Improve CPU_TARGET selection.

src/evaluate.jl
Don't cache packages that have a build script, because caching those results in the build script not firing again during a next run.
=> Be more strict about caching packages.

src/evaluate.jl
Supporting some more packages.
=> More development

src/evaluate.jl
Fixes https://github.com/JuliaLang/julia/issues/46904
=> Mark tests as failed if the log contains certain errors.

src/evaluate.jl
Keep the original failed status so that we don't erroneously report that the tests succeeded.
=> Fix status override on suspicious logs.

src/evaluate.jl
This is more accurate, exluding package installation etc.
=> Pick-up the duration from the test log.

src/evaluate.jl
Otherwise this takes multiple minutes, especially on the actual PkgEval instance (where the package/artifact caches are huge).
=> Verify packages and artifacts using multiple threads.

src/evaluate.jl
Just use ProgressMeter.jl for everything.
=> Simplify output.

src/evaluate.jl
Otherwise we often run into:
```
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:        Error in Timer:
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:        SystemError: opening file "/proc/75678/stat": No such file or directory
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:        Stacktrace:
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:          [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:            @ Base ./error.jl:176
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:          [2] #systemerror#80
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:            @ ./error.jl:175 [inlined]
Nov 10 20:21:50 amdci8 bash[91260]:       From worker 2:          [3] …
```
=> More robust inactivity checking.

src/julia.jl
It's otherwise hard to scroll through the instance's system logs.
=> Hide the Julia build log if nothing goes wrong.

src/evaluate.jl, src/sandbox.jl, src/types.jl, test/runtests.jl
Closes https://github.com/JuliaCI/PkgEval.jl/issues/95
=> Rework and document configuration flags.

src/sandbox.jl
We were already killing Xvfb on exit, so https://github.com/JuliaCI/PkgEval.jl/issues/166 can be closed, but we can be a little more resilient when starting it (trying a couple of times until we find a free display slot).
=> Be more resilient about starting Xvfb.

src/evaluate.jl, src/sandbox.jl, src/types.jl, src/utils.jl
- fixes `rr pack`, we weren't mounting the compilecache
- reduce the log contents, it was too verbose.
- pass values from the test process to the host using files, not by parsing the logs
=> Various fixes and improvements.

src/evaluate.jl
Instead of parsing the log, write to a file after Pkg.add completes.
@KristofferC This changes `:unsatisfiable` to the more general `:uninstallable`.
=> Simplify detection of uninstallable packages.

src/evaluate.jl, src/utils.jl
Fixes:
```
Nov 30 21:27:46 amdci8 bash[97812]:       From worker 2:        Error in Timer:
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:        IOError: getpid: no such process (ESRCH)
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:        Stacktrace:
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:         [1] getpid
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:           @ ./process.jl:620 [inlined]
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:         [2] (::PkgEval.var"#recursive_kill#58")(proc::Base.Process, sig::Int64)
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:           @ PkgEval /storage/pkgeval/dev/PkgEval/src/evaluate.jl:152
Nov 30 21:27:47 amdci8 bash[97812]:       From worker 2:         [3] #53
Nov 30 21:27:47 …
```
=> Better TOCTOU protection for procfs helpers.

src/utils.jl
Typos introduced in https://github.com/JuliaCI/PkgEval.jl/pull/180
=> Fix typo in SystemError handling.

src/evaluate.jl
Otherwise the logs are just really wrong:
```
Dec 01 02:05:11 amdci8 bash[97812]:       From worker 2:        Running tests: 32 remaining (ETA: 0:00:59)
Dec 01 02:12:29 amdci8 bash[97812]:       From worker 2:        Running tests: 22 remaining (ETA: 0:00:41)
Dec 01 02:19:47 amdci8 bash[97812]:       From worker 2:        Running tests: 18 remaining (ETA: 0:00:34)
Dec 01 02:27:04 amdci8 bash[97812]:       From worker 2:        Running tests: 12 remaining (ETA: 0:00:23)
Dec 01 02:34:22 amdci8 bash[97812]:       From worker 2:        Running tests: 8 remaining (ETA: 0:00:16)
Dec 01 02:41:40 amdci8 bash[97812]:       From worker 2:        Running tests: 4 remaining (ETA: 0:00:08)
Dec 01 02:48:58 amdci8 bash[97812]:       From worker 2:        Running tests: 3 remaining (ETA: 0:00:06)
Dec 01 …
```
=> Improve ETA; assume tests will time out.

Artifacts.toml, rootfs/arch.sh, rootfs/debian.sh, rootfs/xvfb.sh, src/sandbox.jl
This should make it easier to use PkgEval, because you don't need Xvfb anymore on the host.
=> Ship and launch Xvfb in an sandbox

Artifacts.toml, Project.toml, src/PkgEval.jl, src/rootfs.jl
Due to a Pkg bug, https://github.com/JuliaLang/Pkg.jl/issues/3269, files are extracted with the wrong permissions.
=> Take rootfs artifact extraction into our own hands

src/evaluate.jl
This should improve accuracy of test duration measurements when running on a loaded machine. Hopefully that fixes the issue we've been seeing with `crun` where (possibly due to scheduling order, or due to cgroup restrictions) the wall time is significantly inflated.
=> Measure CPU time instead of wall time.

src/evaluate.jl, src/registry.jl
Since this will be executed after finishing a package evaluation, it's critical this performs well. Iterating the entire registry each time round, and checking every package against the filesystem, is just too slow.
=> Cache registry lookups for package verification.

.github/workflows/ci.yml, src/julia.jl, src/registry.jl, src/types.jl, src/utils.jl
For https://github.com/JuliaCI/Nanosoldier.jl/pull/154
=> Features for package-based PkgEval

src/evaluate.jl, src/julia.jl, src/utils.jl, test/runtests.jl
Trying this out for the next daily to assess the performance impact.
=> Disable pkgimages.

Packages.toml, src/PkgEval.jl, src/evaluate.jl
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/93
=> Make it possible to grant packages more test time

src/evaluate.jl, src/sandbox.jl, src/types.jl, test/runtests.jl
Closes https://github.com/JuliaCI/PkgEval.jl/issues/211
=> Make it possible to disable separate precompilation

src/sandbox.jl, src/types.jl, test/runtests.jl
Addresses part of https://github.com/JuliaCI/PkgEval.jl/issues/198. Chaos mode requires a BugReporting.jl addition.
=> Make threads explicitly configurable.

src/sandbox.jl
=> Set ENV["LANG"] = "C.UTF-8" by default

Packages.toml, src/PkgEval.jl, src/evaluate.jl
Closes https://github.com/JuliaCI/PkgEval.jl/issues/217
=> Keep track of important packages that should not get blacklisted

src/evaluate.jl
Also adapts to https://github.com/JuliaLang/julia/pull/52695
=> Identify more failures.

src/evaluate.jl, src/utils.jl
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/248
=> Deliver SIGUSR1 to all Julia child processes.

src/evaluate.jl, src/registry.jl
Hopefully this improves compilecache reuse.
=> Sort jobs by number of dependencies.

scripts/test.jl
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/216
=> Bail out quicker when we can't test

scripts/test.jl
Closes https://github.com/JuliaCI/PkgEval.jl/issues/213; I don't think we need to do anything special. Pkg doesn't override `--inline`, so it would be the same in the test process as in the parent process. And if the user has specified `--inline` through `julia_args`, we already propagate that to the precompilation environment.
=> Document CLI flags set for precompilation.

scripts/test.jl
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/222
=> Set ENABLE_GDBLISTENER when running under rr.

src/julia.jl
This caused an issue recently where a broken Julia commit made PkgEval hang.
=> Use a timeout when building Julia.

Packages.toml
Following https://github.com/FedeClaudi/Term.jl/pull/245, fixing https://github.com/FedeClaudi/Term.jl/issues/237.
cc @maleadt .
=> remove `Term` from blacklist

.github/workflows/ci.yml
Fixes https://github.com/JuliaCI/PkgEval.jl/issues/274
EDIT: Well, that was easier than expected.
=> Try running on 24.04.

src/sandbox.jl
Fixes https://github.com/KristofferC/TimerOutputs.jl/pull/202
=> Put Julia on PATH.
